Sphericalmercator module
CartoDB/carto-spatial-extension pull request #32
Opened 2021-02-17 14:28 UTC by vdelacruzb

2021-02-18 13:00 UTC, ibrahimmenem approved these changes
:+1: for ci.yml

2021-03-01 11:46 UTC, Algunenano commented on sphericalmercator/README.md
> +# Spherical Mercator
It would nice to have a description about what it is, where it comes from...

2021-03-01 11:52 UTC, Algunenano commented on sphericalmercator/bq/doc/REFERENCE.md
> +{{% bannerNote type="code" %}}
Please don't use `NUMERIC`. Also, I have no idea what this is supposed to be returning from the description so that's not a good signal.

2021-03-01 11:56 UTC, Algunenano requested changes
What's the difference between this and quadkeys? What does this library offers that isn't covered by the quadkey module and why isn't it better to add it there?

2021-03-01 11:56 UTC, Algunenano commented on sphericalmercator/bq/doc/REFERENCE.md
> +#### XYZ
Are we using this (or the other function). How is this different from quadkey or what you can achieve with quadkeys? Looks pretty similar to me.

2021-04-16 08:48 UTC, Jesus89 commented
Won't be included for now

2021-04-16 08:48 UTC, closed without merging