Proj module
CartoDB/carto-spatial-extension pull request #33
Opened 2021-02-18 08:44 UTC by vdelacruzb

2021-02-18 12:59 UTC, ibrahimmenem approved these changes
:+1: for the owned file ci.yml

2021-03-01 12:56 UTC, Algunenano requested changes

2021-03-01 12:56 UTC, Algunenano commented on proj/bq/test/proj_integration.js
> +    it ('Proj method should work', async () => {
I'm missing some tests with invalid data (invalid projections, invalid/incomplete coordinates) and checks to confirm this works with arrays > 1.

2021-03-01 12:56 UTC, Algunenano commented on proj/README.md
> +Based on http://proj4js.org/.
Please document where the `proj.js` file comes from (source, version..., etc).

2021-04-16 08:47 UTC, Jesus89 commented
Won't be included for now

2021-04-16 08:47 UTC, closed without merging