Tiler quadkey support
CartoDB/carto-spatial-extension pull request #43
Opened 2021-03-08 15:39 UTC by vdelacruzb

2021-03-08 16:00 UTC, Algunenano requested changes
Code looks good, but I don't like the name (it doesn't reflect what is doing and references a different module altogether).

2021-03-08 16:19 UTC, vdelacruzb commented
Renamed the function to LONGLAT_ASQUADINTLIST. Normally we are using LONGLAT_ for functions that accepts map coordinates.  Was thinking of a word that could sum up "Per zoom level", any suggestion?

2021-03-09 15:10 UTC, vdelacruzb commented
There was a bug in quadintFromLocation sending the wrong zoom level to get a quadint. This was causing the tiler to not create the tilesets properly.
Also reduced the latitude limits on tests, since quadintFromLocation get messed when we get too close to the poles.

2021-03-09 15:27 UTC, Algunenano commented on quadkey/bq/doc/REFERENCE.md
> +### quadkey.LONGLAT_ASQUADINTLIST
I would add `_RESOLUTION` or something like that here, since you are calculating a subcell of the tile (based on the resolution).

2021-03-09 15:27 UTC, Algunenano requested changes
> Also reduced the latitude limits on tests, since quadintFromLocation get messed when we get too close to the poles.

Detecting this was great, but the solution you applied is the opposite of great. I don't think we want to remove the tests, instead we should make sure the code handles it. For example, the tiler clips the latitude to ± 86, but we could be more conservative and use the exact 85.06 defined for webmercator (https://epsg.io/3857)

2021-03-09 15:28 UTC, Algunenano commented
Keep in mind that users of BigQuery (or any other geospatial database) can, and likely many will, have data around the poles, so crashing or returning rubish isn't great. I prefer clipping to the nearest representable quadkey/webmercator point in those situations.

2021-03-09 16:38 UTC, Algunenano approved these changes
:+1:

2021-03-09 16:41 UTC, merged