update kring function
CartoDB/carto-spatial-extension pull request #44
Opened 2021-03-10 14:55 UTC by vdelacruzb

The function KRING should accept different distances.
*Notice that the test values where just reordered for the new implementation, but the values contained are the same. It's just that deepEqual complains if the order is not exactly the same.

2021-03-10 16:15 UTC, Algunenano requested changes
> Notice that the test values where just reordered for the new implementation, but the values contained are the same. It's just that deepEqual complains if the order is not exactly the same.

Then sort them and check them sorted, otherwise the test is highly likely to break.

2021-03-10 16:15 UTC, Algunenano commented on quadkey/bq/test/kring_integration.js
> +        assert.deepEqual(rows[0].kring6,[791032102930, 791032102898, 791040491506, 791048880114, 791048880146, 791048880178, 791040491570, 791032102962, 791032102930, 791032102898, 791040491506, 7910
I see lots of duplicates here, so something is going on.

2021-03-10 16:15 UTC, Algunenano commented on quadkey/bq/sql/KRING.sql
> +        distance = 0;
Isn't 0 distance the own `quadint`? So IMO NULL -> 1, which should return the old behaviour.

2021-03-11 09:07 UTC, vdelacruzb commented
- Updated the approach of the function and moved it to quadint.js.
- Added default distance as 1.
- Added tests.
- Fix integration_tests

2021-03-11 09:27 UTC, Algunenano approved these changes

2021-03-11 09:33 UTC, merged